### ISSUE TITLE
[Question] Is there a need for admin-perms

### ISSUE THREAD

**Issue by FishingHacks** [ZoeyVid/Mod-Installer#14]
I didn't found (yet) a reason to require Administrator permissions, as winget doesn't need any, and the other operations should work without Administrator Permissions on a non-restricted system (i don't even know, if a restricted system exists)

**Comment by Zoey2936** [comment]
It's needed to Install / Update Files inside the %ProgramFiles% folder, maybe I can move it into another folder

**Comment by FishingHacks** [comment]
ah, didn't see the %ProgramFiles%

**Comment by Zoey2936** [comment]
You should reinstall the Mod-Installer, then it should work without them

**Comment by FishingHacks** [comment]
i am not using it, just a bit of caring for the project :>
